### PR TITLE
Add operational metrics for batch metrics api

### PR DESCRIPTION
**Pull request by ricardolstephen**
*Fixes #:*
N/A

*Description of changes:*
* READER_METRICSDB_ACCESS_ERRORS: errors accessing metricsdb files
* METRICSDB_FILE_SIZE: size of generated metricsdb files
* BATCH_METRICS_ENABLED: whether or not batch metrics is enabled
* BATCH_METRICS_HTTP_CLIENT_ERROR: number of bad batch metrics requests
* BATCH_METRICS_HTTP_HOST_ERROR: number of batch metrics requests where
    the host ran into errors
* BATCH_METRICS_HTTP_SUCCESS: number of successful batch metrics
    requests
* BATCH_METRICS_EXCEEDED_MAX_DATAPOINTS: requests where the user
    requested for more datapoints than the hardcoded limit of 100800
* BATCH_METRICS_QUERY_PROCESSING_TIME: amount of time required to
    process batch metrics requests
* BATCH_METRICS_NUM_METRICSDB_FILES: number of metricsdb files within
    the batch metrics retention period
* BATCH_METRICS_DATA_SIZE: amount of data batch metrics is storing

*Tests:*
- Manually tested that stats get emitted

*If new tests are added, how long do the new ones take to complete*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by yojs — COMMENTED** [review]
Please also add a metric on the total bytes on disk for the metricsdb files that are kept around to support batch-metrics API. Maybe the cleaner can emit that.

**Review by yojs — COMMENTED** [review]
We did make a few changes to the `ReaderMetricsProcessor` can we think of some metrics to add there ?

One metric I can think of is how much time we spent collecting the batch.

**Review by vigyasharma — COMMENTED** [review]
Can we add a metric for number of files (or total disk used) by the metrics db files the batch api retains?

**Review by yojs — APPROVED** [review]
Excellent Ricardo. Great metrics additions

**Review by khushbr — APPROVED** [review]

**Pull request merged**
